### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by zapalotta** [chrishrb/solarlog-exporter#2]
I just wanted to test this container. 

The container crashes on startup:

```
# docker logs solarlog-exporter
Usage: python -m  [OPTIONS]
Try 'python -m  --help' for help.

Error: Missing option '-d' / '--directory'.
```

Any idea?

Best, Dirk

**Comment by chrishrb** [comment]
Hello, 
you have to enter the directory where the solar log files are stored. If you use docker you have to mount a volume and change the command like this (`./tmp` is your local directory):

```yaml
version: '2'
services:
  solarlog-exporter:
    image: chrishrb/solarlog-exporter:latest
    volumes:
      - ./tmp:/data
    command: -d /data
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DB=solarlog
    networks:
      - solarlog
```

Sorry I didn't mention this in the `docker-compose.yml`.
