### ISSUE TITLE
Error: Missing option '-d' / '--directory'.

### ISSUE THREAD

**Issue by zell-mbc** [chrishrb/solarlog-exporter#5]
I really like what you put together here and like to point it to my Solarlog.
Unfortunately I get stuck already when trying to launch the docker images:

```
solarlog-db        | 2022-03-07T12:34:56.       info    found existing boltdb file, skipping setup wrapper      {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
solarlog-db        | 2022-03-07T12:34:56.       info    found existing boltdb file, skipping setup wrapper      {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
solarlog-exporter  | Usage: python -m  [OPTIONS]
solarlog-exporter  | Try 'python -m  --help' for help.
solarlog-exporter  | 
solarlog-exporter  | Error: Missing option '-d' / '--directory'.
```

Probably something very easy, but I don't know much about Python I am afraid.
I tried with the image from your repo as well as built locally. Here's my test docker-compose.yml
```
cat docker-compose.yml 
version: '2'
services:
  solarlog-exporter:
    image: solarlog-exporter:latest
    container_name: solarlog-exporter
    volumes:
      - ./tests/assets:/data
    environment:
      - INFLUXDB_DB=solarlog

  influxdb:
    image: influxdb:2.1-alpine
    container_name: solarlog-db
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DB=solarlog

    volumes:
      - ./influxdb:/var/lib/influxdb2
```

**Comment by chrishrb** [comment]
I forgot that in the example docker-compose.yml, sorry..
you have to pass the argument `-d` with the directory that includes the solarlog data, e.g. `command: -d /data` for this docker example where the volume `./tests/assets` is mounted to `/data`

so your docker-compose.yml would look something like this:
```yml
version: '2'
services:
  solarlog-exporter:
    image: solarlog-exporter:latest
    container_name: solarlog-exporter
    command: -d /data
    volumes:
      - ./tests/assets:/data
    environment:
      - INFLUXDB_DB=solarlog

  influxdb:
    image: influxdb:2.1-alpine
    container_name: solarlog-db
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DB=solarlog

    volumes:
      - ./influxdb:/var/lib/influxdb2
```
